# Site settings
title: Tijs Verkoyen
email: site@verkoyen.eu
author: Tijs Verkoyen
description: This is a site from/about Tijs Verkoyen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://verkoyen.eu" # the base hostname & protocol for your site

# Post settings
permalink: /blog/:year/:month/:title
paginate: 9
paginate_path: "/blog/page-:num/"

# Build settings
markdown: kramdown

gems:
 - jekyll-paginate
